In [1]:
# Import necessary libraries
import pandas as pd
import seaborn as sb
import re

In [2]:
# Read csv into dataframe
df = pd.read_csv('tickets.csv')
names = pd.read_csv('names.csv')
names = names['Full Name'].str.upper().to_frame()
names = names.rename(columns={"Full Name" : "name"})
display(names)

                        name
0                 JORGEN LAW
1                CHONG YI AN
2   PERI ADHITYAN SIVALINGAM
3               JEREMY LEONG
4     HONG JUN HENG CLARENCE
..                       ...
68            LEONG JUN SENG
69                TENG ZI YI
70           LIANG ZHEN YANG
71               MOK JING YI
72              TEO JING WEN

[73 rows x 1 columns]

In [3]:
# Retrieve and rename useful columns
# Replace "Which of our Members..." with the column name of the column that indicates the member's name
memberQuestion = "Which of our Members(NTUSB) did you buy the ticket from? (Put NIL if inapplicable)"
data = df[["Quantity", memberQuestion]]
data = data.rename({memberQuestion: 'member'}, axis=1)
data['member'] = data['member'].str.upper().to_frame()
print("Total number of tickets sold =", data['Quantity'].sum())
display(data)

Total number of tickets sold = 279

     Quantity       member
0           1       ALICIA
1           1       ALICIA
2           1          RYU
3           1          NIL
4           1          NIL
..        ...          ...
274         1     HARRISON
275         1     HARRISON
276         1  MOK JING YI
277         1  MOK JING YI
278         1          NIL

[279 rows x 2 columns]

In [17]:
# Clean up data obtained from Eventbrite
# Warning: run this cell once only!
# To run this cell again, run the previous cell then this one

# Update rows with Matthew's name because why does his name have a fucking comma
data.loc[data['member'] == 'JOSE, MATTHEW ABRAM MENDOZA', 'member'] = 'MATTHEW'

# Split multiple member names into separate rows
data['member'] = data['member'].str.split(r"AND|,|/", expand=False).to_frame()
data['Quantity'] = data['Quantity'] / data['member'].str.len()
data = data.explode('member')
# data['member'] = data['member'].str.strip()

# Update that one entry that has parenthesis wtf
data['member'] = data['member'].str.replace(r"\(.*\)", "")

# Remove <3 and :) because no love for you
data['member'] = data['member'].str.replace("<|3|\(|\)|:", "")

# Update that one entry that misspelt Sue Jean's name
data.loc[data['member'] == 'BLUE JEAN', 'member'] = 'SUE JEAN'

# Update that one entry that put Carol's surname wrong (boo to that friend)
data.loc[data['member'] == 'CAROL LIN', 'member'] = 'CAROL'

# Update that one entry that clarified which Carol they're buying from, thank you but there is only one Carol
data['member'] = data['member'].str.replace("FROM PERCUSSION", "")

# Update that one entry that has Malcolm's middle (?) name, so extra
data.loc[data['member'] == 'MALCOLM PIUS TAN', 'member'] = 'MALCOLM TAN JINHUI'

# Update all entries for Jimmy because Jimmy is not actually in his name
data.loc[data['member'] == 'JIMMY ANG', 'member'] = 'JIMMY'

# Update that one entry of Brenda so it doesn't count into Brendan
data.loc[data['member'] == 'BRENDA', 'member'] = 'BRENDA POH'

# Update any entry that puts Ynez' surname last
data['member'] = data['member'].str.replace("HOOI", "")

# Remove all spaces
data['member'] = data['member'].str.replace(' ', '')

# Display cleaned up data
with pd.option_context('display.max_rows', None,
                       'display.max_columns', None):
    display(data)

print(data['Quantity'].sum())

     Quantity             member
0    1.000000             ALICIA
1    1.000000             ALICIA
2    1.000000                RYU
3    1.000000                NIL
4    1.000000                NIL
5    1.000000       LOWTHIENSHAW
6    1.000000           YUSHUANG
7    1.000000            FADILAH
8    1.000000       HENGHONGHWEE
9    1.000000              CAROL
10   1.000000              CAROL
11   1.000000            SUEJEAN
12   1.000000            SUEJEAN
13   1.000000            SUEJEAN
14   1.000000          ALICIATHE
15   1.000000             ALICIA
16   1.000000          CHARMAINE
17   1.000000              CAROL
18   1.000000               SHAQ
19   1.000000                NIL
20   1.000000            JINGWEN
21   1.000000                NIL
22   1.000000           HONGHWEE
23   1.000000           HONGHWEE
24   1.000000          ALICIATHE
25   1.000000          ALICIATHE
26   1.000000          ALICIATHE
27   1.000000            SUEJEAN
28   1.000000            SUEJEAN
29   1.000000           HONGHWEE
30   1.000000      LIANGZHENYANG
31   1.000000      LIANGZHENYANG
32   1.000000      LIANGZHENYANG
33   1.000000      LIANGZHENYANG
34   1.000000   MALCOLMTANJINHUI
35   1.000000       HENGHONGHWEE
36   1.000000       HENGHONGHWEE
37   1.000000                NIL
38   1.000000           HONGHWEE
39   1.000000               YNEZ
40   1.000000             JINGYI
41   1.000000             JINGYI
42   1.000000             JORGEN
43   1.000000          JORGENLAW
44   1.000000          JORGENLAW
45   1.000000          JORGENLAW
46   1.000000          JORGENLAW
47   0.500000             XAVIER
47   0.500000             LINGYI
48   1.000000          JORGENLAW
49   1.000000          JORGENLAW
50   1.000000           XAVIERYU
51   1.000000           XAVIERYU
52   1.000000                NIL
53   1.000000             JORGEN
54   1.000000                NIL
55   1.000000       HENGHONGHWEE
56   1.000000       HENGHONGHWEE
57   1.000000       HENGHONGHWEE
58   1.000000       HENGHONGHWEE
59   1.000000      CHARMAINEYAOW
60   1.000000      CHARMAINEYAOW
61   1.000000            MALCOLM
62   1.000000          ALICIATHE
63   1.000000             RIYADH
64   1.000000             RIYADH
65   1.000000             RIYADH
66   1.000000             RIYADH
67   1.000000       WONGYUSHUANG
68   1.000000       WONGYUSHUANG
69   1.000000             ALICIA
70   1.000000                NIL
71   1.000000                NIL
72   1.000000               YNEZ
73   1.000000                NIL
74   1.000000            MATTHEW
75   1.000000      CHARMAINEYAOW
76   1.000000      CHARMAINEYAOW
77   1.000000             RIYADH
78   1.000000             RIYADH
79   1.000000             RIYADH
80   1.000000             RIYADH
81   1.000000           HARRISON
82   1.000000           HARRISON
83   1.000000                NIL
84   1.000000                NIL
85   1.000000           XAVIERYU
86   1.000000           XAVIERYU
87   1.000000           XAVIERYU
88   1.000000           XAVIERYU
89   1.000000           XAVIERYU
90   1.000000           XAVIERYU
91   1.000000           XAVIERYU
92   1.000000             ALICIA
93   1.000000           HONGHWEE
94   1.000000               YNEZ
95   1.000000             ALICIA
96   0.333333             ALICIA
96   0.333333               IVAN
96   0.333333            FADILAH
97   1.000000                NIL
98   0.500000      CHARLOTTECHIA
98   0.500000          KOOLISHAN
99   0.500000      CHARLOTTECHIA
99   0.500000          KOOLISHAN
100  0.500000      CHARLOTTECHIA
100  0.500000          KOOLISHAN
101  0.500000      CHARLOTTECHIA
101  0.500000          KOOLISHAN
102  0.500000      CHARLOTTECHIA
102  0.500000          KOOLISHAN
103  0.500000      CHARMAINEYAOW
103  0.500000         MALCOLMTAN
104  1.000000             JORGEN
105  1.000000        SHINDAYOUNG
106  1.000000      CHARMAINEYAOW
107  1.000000          GOHLINGYI
108  1.000000           JIMMYANG
109  1.000000           JIMMYANG
110  1.000000             ALICIA
111  0.500000               YNEZ
111  0.500000            FADILAH
112  1.000000          ALICIATHE
113  1.000000             LINGYI
114  1.000000             LINGYI
115  1.000000             LINGYI
116  1.000000             LINGYI
117  1.000000                NIL
118  1.000000          JORGENLAW
119  1.000000              WEIYI
120  1.000000   MALCOLMTANJINHUI
121  1.000000   MALCOLMTANJINHUI
122  1.000000   MALCOLMTANJINHUI
123  1.000000   MALCOLMTANJINHUI
124  1.000000   MALCOLMTANJINHUI
125  1.000000   MALCOLMTANJINHUI
126  1.000000          JORGENLAW
127  1.000000             ALICIA
128  1.000000               PERI
129  1.000000               PERI
130  1.000000            FADILAH
131  1.000000                NIL
132  1.000000  SRINIKETHKRISHNAN
133  1.000000             LINGYI
134  1.000000             LINGYI
135  1.000000         LEESUEJEAN
136  1.000000         LEESUEJEAN
137  1.000000  SRINIKETHKRISHNAN
138  1.000000  SRINIKETHKRISHNAN
139  1.000000          SRINIKETH
140  1.000000           BILLYONG
141  1.000000           BILLYONG
142  0.333333            SUEJEAN
142  0.333333               PERI
142  0.333333             JEREMY
143  1.000000      CHARLOTTECHIA
144  1.000000      CHARLOTTECHIA
145  1.000000      CHARLOTTECHIA
146  1.000000      CHARLOTTECHIA
147  1.000000      CHARLOTTECHIA
148  1.000000      CHARLOTTECHIA
149  1.000000           HONGHWEE
150  1.000000   MALCOLMTANJINHUI
151  1.000000      CHARMAINEYAOW
152  1.000000      CHARMAINEYAOW
153  1.000000                NIL
154  1.000000              WEIYI
155  1.000000              WEIYI
156  1.000000              WEIYI
157  1.000000             ALICIA
158  1.000000                NIL
159  1.000000                NIL
160  1.000000                NIL
161  1.000000               PERI
162  1.000000               PERI
163  1.000000            MATTHEW
164  1.000000            MATTHEW
165  1.000000       WONGYUSHUANG
166  1.000000       WONGYUSHUANG
167  1.000000                NIL
168  1.000000                NIL
169  1.000000                NIL
170  1.000000          CHARMAINE
171  1.000000             ALICIA
172  1.000000          CHARMAINE
173  1.000000          CHARMAINE
174  1.000000         TEOJINGWEN
175  1.000000         TEOJINGWEN
176  1.000000         TEOJINGWEN
177  1.000000          CHARMAINE
178  1.000000           HARRISON
179  1.000000           HARRISON
180  1.000000       WONGYUSHUANG
181  1.000000           KHAIHENG
182  1.000000           KHAIHENG
183  1.000000           KHAIHENG
184  1.000000           KHAIHENG
185  1.000000           KHAIHENG
186  1.000000           KHAIHENG
187  1.000000           KHAIHENG
188  1.000000        SHINDAYOUNG
189  1.000000        SHINDAYOUNG
190  0.500000             LISHAN
190  0.500000           HARRISON
191  0.500000             LISHAN
191  0.500000           HARRISON
192  0.500000             LISHAN
192  0.500000           HARRISON
193  1.000000         TEOJINGWEN
194  1.000000           HONGHWEE
195  1.000000                NIL
196  1.000000                NIL
197  1.000000             SHEIKH
198  1.000000             SHEIKH
199  1.000000             SHEIKH
200  1.000000      CHARMAINEYAOW
201  1.000000            FADILAH
202  1.000000            FADILAH
203  1.000000           YUSHUANG
204  1.000000           YUSHUANG
205  1.000000          CAROLCHIA
206  1.000000          CAROLCHIA
207  1.000000             ALICIA
208  1.000000           TENGZIYI
209  1.000000          JORGENLAW
210  1.000000          JORGENLAW
211  1.000000       HENGHONGHWEE
212  1.000000                NIL
213  1.000000             ENTONG
214  1.000000             ENTONG
215  1.000000             ENTONG
216  1.000000           HONGHWEE
217  1.000000             JINGYI
218  1.000000     SEANLEEYIHHUNG
219  1.000000     SEANLEEYIHHUNG
220  1.000000     SEANLEEYIHHUNG
221  1.000000          CAROLCHIA
222  1.000000              KELLY
223  1.000000              KEVIN
224  1.000000              KEVIN
225  1.000000          GOHLINGYI
226  1.000000          GOHLINGYI
227  1.000000          GOHLINGYI
228  1.000000           YUSHUANG
229  1.000000            MINGWEI
230  1.000000                NIL
231  1.000000                NIL
232  1.000000      LOWTHIENSHAWN
233  1.000000              CAROL
234  1.000000            SUEJEAN
235  1.000000                NIL
236  1.000000                NIL
237  1.000000                NIL
238  1.000000              CAROL
239  1.000000              DYLAN
240  1.000000              DYLAN
241  1.000000              DYLAN
242  1.000000         LEESUEJEAN
243  1.000000         LEESUEJEAN
244  1.000000         LEESUEJEAN
245  1.000000                NIL
246  1.000000                NIL
247  1.000000           YUSHUANG
248  1.000000           YUSHUANG
249  1.000000           YUSHUANG
250  1.000000           YUSHUANG
251  1.000000           YUSHUANG
252  1.000000            JUNYANG
253  1.000000            JUNYANG
254  1.000000            JUNYANG
255  1.000000            JUNYANG
256  1.000000       LEONARDCHANG
257  1.000000       LEONARDCHANG
258  1.000000       LEONARDCHANG
259  1.000000       LEONARDCHANG
260  1.000000       LEONARDCHANG
261  1.000000            SUEJEAN
262  1.000000       LEEZHENGQUAN
263  1.000000       LEEZHENGQUAN
264  1.000000                NIL
265  1.000000                NIL
266  1.000000             LINGYI
267  1.000000             LINGYI
268  1.000000             LINGYI
269  1.000000             LINGYI
270  1.000000         TEOJINGWEN
271  1.000000         TEOJINGWEN
272  1.000000          BRENDAPOH
273  1.000000             JINGYI
274  1.000000           HARRISON
275  1.000000           HARRISON
276  1.000000          MOKJINGYI
277  1.000000          MOKJINGYI
278  1.000000                NIL

279.0

In [18]:
# Remove spaces from both data frames
# This helps in string comparison in order to do the total sum later on
names['name'] = names['name'].str.replace(' |,|\(|\)', '')

In [19]:
# Get total tickets sold by each member based on entry of their names
rawTicketCount = data.groupby('member')['Quantity'].sum().reset_index()
rawTicketCount = rawTicketCount.sort_values(by=['Quantity'], ascending=False)

# Display all rows of ticketCount
with pd.option_context('display.max_rows', None,
                       'display.max_columns', None,
                       'display.precision', 3):
    display(rawTicketCount)

# Check that total number of tickets sold corresponds to what we know
print(rawTicketCount['Quantity'].sum())

               member  Quantity
42                NIL    35.000
0              ALICIA    11.333
32             LINGYI    10.500
22          JORGENLAW    10.000
58           XAVIERYU     9.000
60           YUSHUANG     9.000
6       CHARLOTTECHIA     8.500
8       CHARMAINEYAOW     8.500
44             RIYADH     8.000
14       HENGHONGHWEE     8.000
15           HONGHWEE     8.000
38   MALCOLMTANJINHUI     8.000
13           HARRISON     7.500
52            SUEJEAN     7.333
26           KHAIHENG     7.000
54         TEOJINGWEN     6.000
1           ALICIATHE     6.000
56       WONGYUSHUANG     5.000
7           CHARMAINE     5.000
4               CAROL     5.000
28         LEESUEJEAN     5.000
30       LEONARDCHANG     5.000
11            FADILAH     4.833
43               PERI     4.333
20             JINGYI     4.000
12          GOHLINGYI     4.000
23            JUNYANG     4.000
55              WEIYI     4.000
31      LIANGZHENYANG     4.000
59               YNEZ     3.500
9               DYLAN     3.000
21             JORGEN     3.000
10             ENTONG     3.000
51  SRINIKETHKRISHNAN     3.000
49        SHINDAYOUNG     3.000
48             SHEIKH     3.000
46     SEANLEEYIHHUNG     3.000
39            MATTHEW     3.000
5           CAROLCHIA     3.000
27          KOOLISHAN     2.500
2            BILLYONG     2.000
41          MOKJINGYI     2.000
25              KEVIN     2.000
29       LEEZHENGQUAN     2.000
18           JIMMYANG     2.000
33             LISHAN     1.500
40            MINGWEI     1.000
24              KELLY     1.000
19            JINGWEN     1.000
53           TENGZIYI     1.000
3           BRENDAPOH     1.000
50          SRINIKETH     1.000
35      LOWTHIENSHAWN     1.000
36            MALCOLM     1.000
47               SHAQ     1.000
45                RYU     1.000
34       LOWTHIENSHAW     1.000
37         MALCOLMTAN     0.500
57             XAVIER     0.500
17             JEREMY     0.333
16               IVAN     0.333

278.99999999999994

In [20]:
# Create temporary column for Cartesian join
names['join'] = 1
rawTicketCount['join'] = 1

# Do a Cartesian join with names and data to consolidate tickets by name
merged = names.merge(rawTicketCount, on='join').drop('join', axis=1)
rawTicketCount.drop('join', axis=1, inplace=True)

# Compare substrings and merge both names and rawTicketCount together
merged['match'] = merged.apply(lambda x: x['name'].find(x['member']), axis=1).ge(0)

# Filter results
filtered = merged.groupby(['name', 'Quantity']).max().reset_index()[['name', 'Quantity', 'match']]
filtered = filtered[filtered['match']][['name', 'Quantity']]

# Do a groupby to get total tickets sold by each member
ticketCount = filtered.groupby('name')['Quantity'].sum().reset_index()

# Clean up ticketCount to remove unnecessary characters
ticketCount['name'] = ticketCount['name'].str.replace('b|\'', '')
ticketCount = ticketCount.sort_values(by=['Quantity'], ascending=False)

# Display all rows of ticketCount
with pd.option_context('display.max_rows', None,
                       'display.max_columns', None,
                       'display.precision', 3):
    display(ticketCount)

# Check that total number of tickets sold corresponds to sum we know
print(ticketCount['Quantity'].sum())

                         name  Quantity
0                   ALICIATHE    17.333
7                   GOHLINGYI    14.500
37               WONGYUSHUANG    14.000
3        CHARMAINEYAOWYUSHANE    13.500
13                  JORGENLAW    13.000
19                 LEESUEJEAN    12.333
38           XAVIERYUZHENGWEI    10.500
23           MALCOLMTANJINHUI     9.500
27          RIYADHAL-MUTTAQIN     8.000
10               HENGHONGHWEE     8.000
9           HARRISONTANHUIJUN     7.500
36               WONGKHAIHENG     7.000
34                 TEOJINGWEN     7.000
24                  MOKJINGYI     6.000
5             CHIAMUILINCAROL     5.000
25  NURFADILAHBINTEABDULLATIF     4.833
26     PERIADHITYANSIVALINGAM     4.333
17                  KOOLISHAN     4.000
18                 LEEJUNYANG     4.000
32          SRINIKETHKRISHNAN     4.000
21              LIANGZHENYANG     4.000
4                   CHENWEIYI     4.000
11            HOOIYUYEONGYNEZ     3.500
29   SHEIKHMUHAMMADAMIRULHAQQ     3.000
35                 THAMENTONG     3.000
30                SHINDAYOUNG     3.000
6              DYLANTEOWENJUN     3.000
14    JOSEMATTHEWABRAMMENDOZA     3.000
20               LEEZHENGQUAN     2.000
1                    BILLYONG     2.000
16            KEVINLAIKITYENG     2.000
28             RYUNAUFALRAFIF     1.000
15                   KELLYLOW     1.000
33                   TENGZIYI     1.000
8                  HANMINGWEI     1.000
2             BRENDAPOHXINHUI     1.000
22              LOWTHIENSHAWN     1.000
31            SOHHONGMINGIVAN     0.333
12                JEREMYLEONG     0.333

213.5